export const fruitsData = [
  { name: "Apple", id: 1 },
  { name: "Banana", id: 2 },
  { name: "Orange", id: 3 },
  { name: "Grapes", id: 4 },
  { name: "Strawberry", id: 5 },
  { name: "Mango", id: 6 },
  { name: "Pineapple", id: 7 },
  { name: "Watermelon", id: 8 },
  { name: "Kiwi", id: 9 },
  { name: "Cherry", id: 10 },
  { name: "Blueberry", id: 11 },
  { name: "Peach", id: 12 },
  { name: "Plum", id: 13 },
  { name: "Pear", id: 14 },
  { name: "Lemon", id: 15 },
  { name: "Lime", id: 16 },
  { name: "Avocado", id: 17 },
  { name: "Pomegranate", id: 18 },
  { name: "Cranberry", id: 19 },
  { name: "Raspberry", id: 20 },
  { name: "Blackberry", id: 21 },
  { name: "Apricot", id: 22 },
  { name: "Cantaloupe", id: 23 },
  { name: "Fig", id: 24 },
  { name: "Guava", id: 25 },
  { name: "Passion Fruit", id: 26 },
  { name: "Persimmon", id: 27 },
  { name: "Dragon Fruit", id: 28 },
  { name: "Kiwano", id: 29 },
  { name: "Star Fruit", id: 30 },
];
